/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIGeneratedTopic: typeof import('./../components/AIGeneratedTopic.vue')['default']
    AllExamPaperStatus: typeof import('./../components/charts/AllExamPaperStatus.vue')['default']
    BatchUploadQuestions: typeof import('./../components/BatchUploadQuestions.vue')['default']
    ChatSkeleton: typeof import('./../components/ChatSkeleton.vue')['default']
    CourseDifficultyChart: typeof import('./../components/charts/CourseDifficultyChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    GithubContributions: typeof import('./../components/charts/GithubContributions.vue')['default']
    MarkdownContext: typeof import('./../components/common/MarkdownContext.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShuJuKu: typeof import('./../components/ShuJuKu.vue')['default']
    StudentCard: typeof import('./../components/StudentCard.vue')['default']
    TestQuestion: typeof import('./../components/TestQuestion.vue')['default']
    TextLoading: typeof import('./../components/TextLoading.vue')['default']
    UserProfile: typeof import('./../components/UserProfile.vue')['default']
    UserProfileFooter: typeof import('./../components/UserProfileFooter.vue')['default']
    WrongQuestionCard: typeof import('./../components/WrongQuestionCard.vue')['default']
  }
}
